### ISSUE TITLE
Add UI for MasterData Settings

### ISSUE THREAD

**Issue by selleiro** [JJConsulting/JJMasterData#46]
**Is your feature request related to a problem? Please describe.**
Ease of configuring database connection

**Describe the solution you'd like**
In the appsettings or web.config file include the path of the database connection UDL file.
Example: 
ConnectionString:"connection.udl"

![image](https://user-images.githubusercontent.com/98551611/200048211-bd03f84d-2411-4758-870c-3619e6910c42.png)

**Comment by gumbarros** [comment]
Good afternoon @selleiro !

I talked with @LucioPelinson .

It is possible to supply connection information for an OleDbConnection in a Universal Data Link (UDL) file; however you should avoid doing so. UDL files are not encrypted, and expose connection string information in clear text. Because a UDL file is an external file-based resource to your application, it cannot be secured using the .NET Framework. UDL files are not supported for SqlClient. (from: https://social.msdn.microsoft.com/Forums/en-US/0bb40f32-86f4-4b6f-a2e0-bc2bdcf07b63/using-sqlconnection-for-udl-file?forum=adodotnetdataproviders)

Also using a OleDbConnection will cause performance problems compared to SqlClient. We also don't have the guarantee it will work with .NET 6 and 7, only .NET Framework. UDL files are not supported on Linux and Mac too.

**Comment by selleiro** [comment]
Hi GumBarros. 

Therefore, I would like you to create an interface screen for us to enter the connection data with the database when opening the site in case this information is not informed in the appsettings.json file.

**Comment by gumbarros** [comment]
> Hi GumBarros.
> 
> Therefore, I would like you to create an interface screen for us to enter the connection data with the database when opening the site in case this information is not informed in the appsettings.json file.

Great, we think this is possible and very useful.

**Comment by gumbarros** [comment]
![image](https://user-images.githubusercontent.com/52143624/203063078-234efc9a-6240-45b1-be44-570f6c46be5e.png)
Good morning @selleiro!  I added the following options to a new option at toolbar called "Application Options". This will be available at Saturn version. This popup will also prompt if no connection string is found at appsettings.json. These settings are also automatically saved to appsettings.json.
