### ISSUE TITLE
JJTextFile incorrect layout popup

### ISSUE THREAD

**Issue by LucioPelinson** [JJConsulting/JJMasterData#50]
**Describe the bug**
When we custom a layout and open a JJTextFile upload files appear in incorrect layout popup 

**Expected behavior**
Open popup without custom layouts

**Screenshots**
![image](https://user-images.githubusercontent.com/28662273/201191106-d3ffd512-894a-4804-ba1a-060789eaddca.png)

**.NET version**
[.NET Framework 4.8 or .NET 6+]

**Comment by gumbarros** [comment]
Possible solutions I'm thinking:
### Create a TextFileController
Problems: Send `JJTextFile` encrypted (huge object) or lose customization state on `JJTextFile`
### Already render the modal on the page without a iFrame. Just hide it using JS.
- Already add the modal to the DOM? 
- Customize `jjpopup.ts` to allow raw HTML strings instead of a URL ?


@LucioPelinson  any ideas to the problem?

**Comment by gumbarros** [comment]
The time has come @LucioPelinson , we are now using raw HTML strings instead of a iframe :)
